### ISSUE TITLE
Waiting for Compliance Check

### ISSUE THREAD

**Issue by BushcraftUSA** [turnkeymobileapps/help-center#37] opened 2017-03-07 06:33 UTC
It has been 3 weeks and your site still lists my app as waiting for compliance check. I have been using the downloaded Android app to connect to my site via your server-side add-on, for 3 weeks.

Can I get an update on my app for BushcraftUSA?

Additionally, I looked at upgrading my account via the PayPal checkout you have and I am being asked for credit card information. I have been using PP for years with two on my businesses and have never seen that. Is that a blip, or ??

**Comment by vbresults** [comment] 2017-03-07 11:01
We are not processing FMA submissions until the middle of the month as we are working on a big release.  Apologies for the delay.

Duplicate of #35

**Closed by vbresults** 2017-03-07 11:01 UTC
Labels: question

**Comment by BushcraftUSA** [comment] 2017-03-07 11:39
Maybe you didn't notice the 2nd part of my ticket, where I mentioned that I was trying to upgrade my account, so it would not be FMA.

**Comment by vbresults** [comment] 2017-03-07 13:03
@BushcraftUSA It looks like this forum's account for created for a demo of the premium version, but then converted to the free version through the member interface.

I did reply to your note about paypal in an edit a few minutes after my original reply.

**Comment by BushcraftUSA** [comment] 2017-03-07 23:01
So would it be better to redo it when you roll out the new version, or will it update automatically? I really need to replace Tapatalk. I have disabled them already, but 67% of my membership uses mobile devices.

**Comment by vbresults** [comment] 2017-03-08 00:42
@BushcraftUSA When we roll out the new version, I'll make sure to update all of the built apps -- you'll just need to upgrade the add-on and download the new app.

I don't think I've heard of the drop-down issue you've seen before, but the menu works in a totally different way in the upcoming release so it will be fixed.
