### ISSUE TITLE
IOS App

### ISSUE THREAD

**Issue by psx123** [turnkeymobileapps/help-center#31] opened 2017-01-29 18:11 UTC
On IOS 10.3 the app crashes, my members have been reporting.

**Comment by vbresults** [comment] 2017-01-29 19:11
@psx123 What is your app id?

**Comment by psx123** [comment] 2017-01-30 01:25
1174119181

**Comment by vbresults** [comment] 2017-02-02 07:14
@psx123 When does it crash specifically?

**Comment by psx123** [comment] 2017-02-03 07:29
When opening

**Comment by vbresults** [comment] 2017-02-05 00:16
@psx123 What specific version of the app are the people reporting these crashes using?

**Comment by psx123** [comment] 2017-02-05 04:17
The latest one

**Comment by vbresults** [comment] 2017-02-08 11:03
@psx123 Having trouble reproducing this -- does this happen for 10.3+ exclusively or also <= 10.2?  If so, what devices?  Sorry for all the questions, just trying to recreate the crash

**Comment by vbresults** [comment] 2017-02-21 01:57
Due to major changes in upcoming 2.2, closing this for now.  If the issue is still there, please re-open this ticket.

**Closed by vbresults** 2017-02-21 01:57 UTC
Labels: 2.x, ios
